version: "3.8"
services:
  nextjs:
    container_name: nextjs
    build:
      context: ./
      dockerfile: ./docker/node/Dockerfile
      target: runner
    user: root
    volumes:
      - .:/app
    command: npm run dev
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
