version: "3.8"
services:
  nextjs:
    container_name: nextjs
    build:
      context: ./
      dockerfile: ./docker/node/Dockerfile
      target: runner
    image: //Removed for safety purposes/nextjs-psite:latest
    ports:
      - "3000:3000"
    platform: linux/amd64
  nginx:
    restart: unless-stopped
    container_name: nginx_web
    build:
      dockerfile: docker/nginx/Dockerfile
      context: .
    image: //Removed for safety purposes/nginx-psite:latest
    platform: linux/amd64
