version: "3.8"
services:
  nextjs:
    container_name: nextjs
    build:
      context: ./
      dockerfile: ./docker/node/Dockerfile
      target: runner
    image: 028352660330.dkr.ecr.us-east-1.amazonaws.com/nextjs-psite:latest
    ports:
      - "3000:3000"
    platform: linux/amd64
  nginx:
    restart: unless-stopped
    container_name: nginx_web
    build:
      dockerfile: docker/nginx/Dockerfile
      context: .
    image: 028352660330.dkr.ecr.us-east-1.amazonaws.com/nginx-psite:latest
    platform: linux/amd64
