version: "3.8"
services:
  nextjs:
    container_name: nextjs
    build:
      context: ./
      dockerfile: ./docker/node/Dockerfile
      target: runner
    user: root
    volumes:
      - .:/app
    command: npm run dev
    ports:
      - "3000:3000"
    networks:
      - intranet
    environment:
      NODE_ENV: development
  nginx:
    restart: unless-stopped
    container_name: nginx_web
    build:
      dockerfile: docker/nginx/Dockerfile
      context: .
    ports:
      - "80:80"
      - "443:443"
    networks:
      - intranet
    volumes:
      - ./docker/nginx/next.conf:/etc/nginx/conf.d/next.conf
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./ssl/localhost.crt:/etc/ssl/certs/localhost.crt
      - ./ssl/localhost.key:/etc/ssl/private/localhost.key
      - ./src/public/:/var/www/html/
    depends_on:
      - nextjs

networks:
  intranet:
